### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by 11510880** [mtobeiyf/audio-classification#1]
Hello, when I run nn.py and cnn.py, the spyder showed that  AttributeError: 'ProgbarLogger' object has no attribute 'log_values' . It seems that something wrong the keras

**Comment by imfing** [comment]
I tested the code and it didn't throw that error.
Make sure you have the feature files correctly generated, i.e. `feat.npy` and `label.npy`. Run `feat_extract.py` at first.
Download the dataset from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YDEPUT

Also, the `data` directory should have the following structure:
```
data
├─001 - Dog bark
└─002 - Rain
```

**Comment by 11510880** [comment]
OK, it is fine , thanks.

**Comment by mvrozanti** [comment]
@11510880 did you find a fix for the AttributeError you mentioned?

**Comment by 11510880** [comment]
Sorry, I can't remember clearly. But I guess I have fixed that error, which may be related with Python edition

**Comment by mvrozanti** [comment]
I'm running python 2.7. [This](https://github.com/keras-team/keras/issues/3684) implies the training set is of size 0.
Except my data folder looks like this:

```
├── 001 - Cat
│  ├── cat_1.wav
│  ├── cat_2.wav
│  ├── cat_3.wav
│   ...
--
└── 002 - Dog
   ├── dog_barking_0.wav
   ├── dog_barking_1.wav
   ├── dog_barking_2.wav
│   ...
```

`.npy` files seem way too small to be useful though:

> du -h *.npy

```
512	feat.npy
512	label.npy
```
@mtobeiyf does this look right?

**Comment by imfing** [comment]
I reviewed the code of `feature_extract.py` and found this line https://github.com/mtobeiyf/audio-classification/blob/7fd8f2e0cd44347fd0d98074b2c06586d507e47b/feat_extract.py#L39
The file extension is limited to `.ogg` files. Change that to `.wav` may solve that problem.
If you can make this work for both `.ogg` and `.wav` you can create a PR to this repo.

**Comment by mvrozanti** [comment]
Thank you for responding quickly, I don't know how I missed that. 

```
$ du -h *.npy # now returns
420K	feat.npy
4.0K	label.npy
```

I managed to have it trained! yay

I'm a bit confused on how to predict a single ogg sample and list results though.

**Comment by mvrozanti** [comment]
When I replace 

https://github.com/mtobeiyf/audio-classification/blob/7fd8f2e0cd44347fd0d98074b2c06586d507e47b/feat_extract.py#L39

With `def parse_audio_files(parent_dir,sub_dirs,file_exit='*.wav'):`, I get `npy` files that are the same in size as the `npy` extracted from `ogg` but different in hash. I'm not sure if `librosa` can do `wav` files the same way as `ogg` so I'm going to pursue predicting a single original `ogg` file and see if it does well. If I can find out how to predict, that is :laughing:

**Comment by imfing** [comment]
@mvrozanti 
Cool.
Well, I guess there may be slight differences between the features extracted from `.wav` and `.ogg` files.
You can do an inspection to the features and see if they are valid for the following prediction.
