### ISSUE TITLE
 wav file does not work

### ISSUE THREAD

**Issue by ZhongLIFR** [mtobeiyf/audio-classification#10]
When I try to put wav files in data directory, it appears:
[Error] extract feature error in data_wav/6/148835-6-0-0.wav. Frequency band exceeds Nyquist. Reduce either fmin or n_bands.
Solution: tune "fmin" parameter in function "extract_feature(file_name=None)" as follows:
contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate, fmin=180.0).T,axis=0)

**Comment by imfing** [comment]
Okay, thanks. It's a problem related to the audio files.
I'll close this issue for now.
