### ISSUE TITLE
still getting error after executing the command cnn.py -p

### ISSUE THREAD

**Issue by abhijeet3486** [mtobeiyf/audio-classification#15]
Steps which I did..
1)download ESC-10 dataset then inserted in data directory
2)executed command python feat_extract.py
3)4 file are created feat.py,lable.py,predict_feat,predict_filenames
4)executed command svm.py and output is fitting... acc=0.756
5)executed nn.py
6)executed cnn.py -t
7)putting single sample audio at predict folder and executed the command cnn.py -t but erorr occures like

Traceback (most recent call last):
  File "cnn.py", line 123, in <module>
    main(args)
  File "cnn.py", line 109, in main
    elif args.predict: predict(args)
  File "cnn.py", line 73, in predict
    pred = model.predict_classes(X_predict)
  File "C:\Users\Abhijeet\Anaconda3\envs\tfp3.6\lib\site-packages\keras\engine\s
equential.py", line 268, in predict_classes
    if proba.shape[-1] > 1:
AttributeError: 'list' object has no attribute 'shape'

**Comment by abhijeet3486** [comment]
also i am not understand the meaning of Predict files by either:

    Putting target files under predict/ directory and running cnn.py -p
    Recording on the fly with cnn.py -P

**Comment by imfing** [comment]
You need to extract the feature of that single file by running `feat_extract.py` again.
It's a little confusing, but take a look at this `predict` function, you'll figure it out.
https://github.com/mtobeiyf/audio-classification/blob/master/cnn.py#L65
