### ISSUE TITLE
Can I use .wav to train instead of .ogg

### ISSUE THREAD

**Issue by liu-ioa** [mtobeiyf/audio-classification#18]

**Comment by dmumtaz** [comment]
Did .wav work for you? It doesn't seem to accept the .wav format even when I changed the extension in the feat_extract.py file.

**Comment by liu-ioa** [comment]
Yeah，I did，I used librosa. 
---原始邮件---
发件人:"dmumtaz"<notifications@github.com>;
发送时间:2020年1月19日(星期天) 下午5:57
收件人:"mtobeiyf/audio-classification"<audio-classification@noreply.github.com>;
抄送人:"2834156593lq"<2834156593@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [mtobeiyf/audio-classification] Can I use .wav to train insteadof .ogg (#18)


Did .wav work for you? It doesn't seem to accept the .wav format even when I changed the extension in the feat_extract.py file.
 
&mdash;

**Comment by dmumtaz** [comment]
Can you provide the code and explain how it worked? 

I changed the code in **feat_extract.py** as:
**def parse_audio_files(parent_dir,file_ext='*.wav'):** 

But it seems to work for only some .wav (file1.wav) files while for others it gives error such as: 
1. Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity. (file2.wav)
2. UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn('Trying to estimate tuning from empty frequency set.')  (file3.wav)

EXamples given in zip file:
[006 - test.zip](https://github.com/mtobeiyf/audio-classification/files/4082544/006.-.test.zip)

**Comment by liu-ioa** [comment]
That surely can't work. you are supposed to change the package of reading audio file. ------------------ 原始邮件 ------------------
发件人: "dmumtaz"<notifications@github.com>
发送时间: 2020年1月19日(星期天) 晚上7:07
收件人: "mtobeiyf/audio-classification"<audio-classification@noreply.github.com>;
抄送: "2834156593lq"<2834156593@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mtobeiyf/audio-classification] Can I use .wav to train insteadof .ogg (#18)



I changed the code in feat_extract.py as:
 def parse_audio_files(parent_dir,file_ext='*.wav'):
 
Can you provide the code and explain how it worked? The present code seems to work for only some .wav (file1.wav) files while for others it gives error such as:
  
Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity. (file2.wav)
 
UserWarning: Trying to estimate tuning from empty frequency set.
 warnings.warn('Trying to estimate tuning from empty frequency set.')  (file3
 006 - test.zip
 .wav)
  
&mdash;

**Comment by dmumtaz** [comment]
Thanks!
I replaced:
**X, sample_rate = sf.read(file_name, dtype='float32') #for reading ogg** 
with:       
**X, sample_rate= librosa.load(file_name, sr=None) #for reading .wav**

**Comment by imfing** [comment]
@dmumtaz Thanks, I'm gonna close this issue.
