### ISSUE TITLE
Error! feat.npy is not UTF-8 encoded 

### ISSUE THREAD

**Issue by hibakhanam** [mtobeiyf/audio-classification#2]
Hi , i am using the same structure as you said  but when i run feat_extract.py ,it run smoothly and gives me this output :

extract .ipynb_checkpoints features done
extract 001 - Dog bark features done
extract 002 - Rain features done
extract 003 - Sea waves features done
extract 004 - Baby cry features done
extract 005 - Clock tick features done
extract 006 - Person sneeze features done
extract 007 - Helicopter features done
extract 008 - Chainsaw features done
extract 009 - Rooster features done
extract 010 - Fire crackling features done

but in feat.npy, it says Error! feat.npy is not UTF-8 encoded 

please help me to understand this and how i can resolve it

**Comment by imfing** [comment]
Seems that you didn't have generated anything. Take a look at your `data` directory. 
https://github.com/mtobeiyf/audio-classification/issues/1#issuecomment-398076185
Typically, the process may take some time rather than a few seconds.

**Comment by hibakhanam** [comment]
i checked my data directory . it is of the same structure as you mentioned in #1 (comment) 
but still there is issue 
please help me for GOD sake

**Comment by imfing** [comment]
Perhaps you need to remove all the other files (like `*.xls` `*.txt`...) and should remain the directories like `001 - Dog bark` in the extracted folder.

**Comment by hibakhanam** [comment]
there is no such files exists in that folder where code is placed 
and yes directories are same..
data\001 - Dog bark

**Comment by imfing** [comment]
I mean in the `data` directory. 
Download the dataset from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YDEPUT

In the original dataset zip file, there should be some files: 
![image](https://user-images.githubusercontent.com/5097752/42344132-3c906cd4-8050-11e8-84ae-429c30fc7b5c.png)
Delete them
and remain the directory like this
![image](https://user-images.githubusercontent.com/5097752/42344181-591a9c62-8050-11e8-9c05-15a9ea62957d.png)

Make sure you have `.ogg` files in each directory.
![image](https://user-images.githubusercontent.com/5097752/42344210-72b3d9cc-8050-11e8-9e45-7318e74b1adc.png)

**Comment by hibakhanam** [comment]
this is my data directory 
![image](https://user-images.githubusercontent.com/39904968/42344414-b9c53666-80b5-11e8-92b2-de0a1784872f.png)
and these are files in each directory 
![image](https://user-images.githubusercontent.com/39904968/42344468-df5e0998-80b5-11e8-902e-14727e45e2e9.png)

i am confused where i am wrong

**Comment by imfing** [comment]
I have no idea. There is no such errors when I run the code myself.
You should debug the code yourself to see if the output for each step is correct. 
If you got correct feature vectors, then saving them to a `npy` file will cause no problem.

**Comment by hibakhanam** [comment]
i run this code on spyder notebook and i run successfully 
thanks for your much patience 
i have only one question now 
you extracted mfcc, chroma, mel spectrogram etc so in feat.npy file how can i locate what value is of which feature?
this is feature numpy array
![image](https://user-images.githubusercontent.com/39904968/42345240-1d9764dc-80b8-11e8-8c8d-a93578c81146.png)

here is label numpy array

![image](https://user-images.githubusercontent.com/39904968/42345288-46559dbc-80b8-11e8-99be-da9739c7bf8a.png)

![image](https://user-images.githubusercontent.com/39904968/42345311-5283eda0-80b8-11e8-9bfa-9da2c4f2aa1e.png)

**Comment by imfing** [comment]
Have a look at the code and you will see. They are simply stacked together.
