### ISSUE TITLE
The class labels seem to differ from the actual labels.

### ISSUE THREAD

**Issue by dmumtaz** [mtobeiyf/audio-classification#21]
When I tried to predict the classes there seemed to be some kind of pattern. The class names given by folder is different from the predicted name:
**Name, Predicted,Actual**
rain=0,2
seawaves=1,3
baby=2,4
clock=3,5
sneeze=4,6
helicopter=5,7
chainsaw=6,8
rooster=7,9
firecracker=8,10
dog=13,1
What could be the reason?

**Comment by imfing** [comment]
I think you can try printing the labels or other variables, and see which step caused this issue.
There may be something messed up in the code. Please point out or make a PR once you find out.

**Comment by dmumtaz** [comment]
The labels from feat_extract.py give expected result when printed here:
 labels = np.append(labels, fn.split('/')[1])
 or
labels = np.append(labels, label)

but there seem to be some problem when training the cnn -p . It gives class names which are not present in the labels list.

**Comment by imfing** [comment]
See https://github.com/mtobeiyf/audio-classification/issues/19#issuecomment-577007103
