### ISSUE TITLE
I get an index 12 out of bounds when I run the cnn.py -t 

### ISSUE THREAD

**Issue by skiwheelr** [mtobeiyf/audio-classification#22]
So this happened with both my own OGG data and the ESC data, with one OGG file in the predict folder.

Everything went normally, the SVN and MLP worked. Then I tried the CNN:

_

> **Phonecian:audio-classification skiwheelr$ python3 cnn.py -t
> Using TensorFlow backend.
> 2020-04-03 23:29:32.002190: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-04-03 23:29:32.015288: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8e13dfbac0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-04-03 23:29:32.015310: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> Traceback (most recent call last):
>   File "cnn.py", line 124, in <module>
>     main(args)
>   File "cnn.py", line 109, in main
>     if args.train: train(args)
>   File "cnn.py", line 51, in train
>     y_train = keras.utils.to_categorical(y_train, num_classes=class_count)
>   File "/usr/local/lib/python3.7/site-packages/keras/utils/np_utils.py", line 52, in to_categorical
>     categorical[np.arange(n), y] = 1
> IndexError: index 12 is out of bounds for axis 1 with size 12**

What could be causing this? There is enough data.

**Comment by imfing** [comment]
This line caused the problem `y_train = keras.utils.to_categorical(y_train, num_classes=class_count)`.
Not sure what is the actual reason for it. 
You can run feature extraction first and see how `y_train` and `class_count` looks like.
