### ISSUE TITLE
index out of bound

### ISSUE THREAD

**Issue by ByTusharGarg** [mtobeiyf/audio-classification#3]
when executing nn.py gives following error

Using TensorFlow backend.
Traceback (most recent call last):
  File "nn.py", line 37, in <module>
    y_train = keras.utils.to_categorical(y_train-1, num_classes=10)
  File "C:\Users\TUSHAR\Anaconda3\lib\site-packages\keras\utils\np_utils.py", line 32, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 21 is out of bounds for axis 1 with size 10

**Comment by 98mprice** [comment]
I am getting a similar error

`IndexError: index 22 is out of bounds for axis 1 with size 10`

**Comment by imfing** [comment]
This PR #4 may solve your problem.
