### ISSUE TITLE
errors in cnn.py

### ISSUE THREAD

**Issue by ZhongLIFR** [mtobeiyf/audio-classification#9]
I got two errors when executing the file "cnn.py".
1. Unresolved reference 'feat_extract' when we define the function:train(args).
solution for this error: we should use "import feat_extract" instead of using "from feat_extract import *";
2.Unresolved reference 'X_predict' when we define the function: predict(args).
"X_predict = np.expand_dims(X_predict, axis=2)", the "X_predict" in the right side is not pre-defined nor pre-produced.
solution for this error: we can replace "X_predict" by "predict_feat_path".

**Comment by imfing** [comment]
Thanks for the solutions. 👍 Fixed
And welcome any PR to make this repository better. 😄
